vim.cmd([[autocmd BufEnter,BufReadPre,BufRead,BufNewFile *.v setlocal filetype=vlang]])
vim.cmd([[set guifont=CaskaydiaCove\ Nerd\ Font\ Mono:h12]])
require('slumber.core.opts')
require('slumber.core.packers')
require('slumber.core.mappings')
